In [1]:
%%time
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn import Embedding

device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cpu
CPU times: user 1.93 s, sys: 355 ms, total: 2.28 s
Wall time: 4.4 s


---
## PyTorch Features

In [2]:
torch.randint(low=-100, high=100, size=(6,), dtype=torch.int32, device=device, requires_grad=False)

tensor([-59,  50,  71,  66, -46,  96], dtype=torch.int32)

In [3]:
torch.tensor(data = [[91, -71,  77],
                     [40,  49, -26],
                     [91, -71,  77]], dtype=torch.int32, device=device, requires_grad=False)

tensor([[ 91, -71,  77],
        [ 40,  49, -26],
        [ 91, -71,  77]], dtype=torch.int32)

In [4]:
torch.zeros(size=(4,8), dtype=torch.int32, device=device, requires_grad=False)

tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]], dtype=torch.int32)

In [5]:
torch.ones(size=(4,8), dtype=torch.int32, device=device, requires_grad=False)

tensor([[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.int32)

In [6]:
torch.empty(size=(2,6), dtype=torch.int32, device=device, requires_grad=False)

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0]], dtype=torch.int32)

In [7]:
torch.arange(start=0, end=10, step=2, dtype=torch.int32, device=device, requires_grad=False)

tensor([0, 2, 4, 6, 8], dtype=torch.int32)

In [8]:
torch.linspace(start=0, end=20, steps=6, dtype=torch.float32, device=device, requires_grad=False)

tensor([ 0.,  4.,  8., 12., 16., 20.])

In [9]:
torch.logspace(start=0, end=20, steps=6, base = 10.0, dtype=torch.float32, device=device, requires_grad=False)

tensor([1.0000e+00, 1.0000e+04, 1.0000e+08, 1.0000e+12, 1.0000e+16, 1.0000e+20])

In [10]:
torch.logspace(start=0, end=20, steps=6, base = 2.0, dtype=torch.float32, device=device, requires_grad=False)

tensor([1.0000e+00, 1.6000e+01, 2.5600e+02, 4.0960e+03, 6.5536e+04, 1.0486e+06])

In [11]:
torch.eye(n=5, m=5, dtype=torch.float32, device=device, requires_grad=False)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
torch.eye(n=5, dtype=torch.float32, device=device, requires_grad=False)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
a = torch.empty(size=(2,6), dtype=torch.int32, device=device, requires_grad=False)
torch.empty_like(a)

tensor([[-897653952,      22344, -897649488,      22344,          1,          0],
        [         0,          0,          0,          0,          1,          0]],
       dtype=torch.int32)

### Intermediate Features
---

In [14]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9]) # 10% chance for event 0 (index) and 90% chance for event 1 (index)

samples = torch.multinomial(input=probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 0, 1, 1, 1, 1, 1, 1, 1])


In [15]:
tensor1 = torch.tensor([1,2,3,4])
tensor2 = torch.tensor([5])

torch.cat([tensor1, tensor2], dim=0)

tensor([1, 2, 3, 4, 5])

In [16]:
torch.tril(input=torch.ones(size=(5,5)))

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [17]:
torch.triu(input=torch.ones(size=(5,5)))

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [18]:
tensor1 = torch.tril(input=torch.ones(size=(5,5)))

output = torch.zeros(size=(5,5)).masked_fill(tensor1 == 0, float("-inf"))
print(output)

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])


In [19]:
torch.exp(input=output)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [20]:
inputs = torch.zeros(size=(4,3,2,1))
inputs.transpose(dim0=0, dim1=3).shape

torch.Size([1, 3, 2, 4])

In [21]:
tensor1 = torch.tensor([1,2,3,4])
tensor2 = torch.tensor([5,6,7,8])
tensor3 = torch.tensor([9,8,7,6])
tensor4 = torch.tensor([5,4,3,2])

# stack the above tensors in a new dimension
print(torch.column_stack(tensors=[tensor1,tensor2,tensor3,tensor4]) == torch.dstack(tensors=[tensor1,tensor2,tensor3,tensor4]))
print(torch.hstack(tensors=[tensor1,tensor2,tensor3,tensor4]))
print(torch.stack(tensors=[tensor1,tensor2,tensor3,tensor4], dim=0))

tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 8, 7, 6, 5, 4, 3, 2])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 8, 7, 6],
        [5, 4, 3, 2]])


In [22]:
import torch.nn as nn

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(in_features=3, out_features=3, bias=False)
print(linear(sample))

tensor([ 8.8624, -4.6313,  0.3985], grad_fn=<SqueezeBackward4>)


### `torch.nn.functional` module
---

In [23]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])
F.softmax(input=tensor1, dim=0)

tensor([0.0900, 0.2447, 0.6652])

### `torch.nn.Embedding` module
---

In [24]:
from torch.nn import Embedding

# Define an embedding layer for words with 10,000 unique words and each word represented by a vector of size 100
embedding_layer = Embedding(num_embeddings=10000, embedding_dim=100)

# Input: An array of word indices
input_data = torch.LongTensor([1, 5, 3, 8])

# Apply the embedding layer to convert indices into vectors
embedded_vectors = embedding_layer(input_data)

# The result is a tensor of shape (4, 100), with each row representing a word as a 100-dimensional vector.
print(embedded_vectors.shape)
embedded_vectors[0]

torch.Size([4, 100])


tensor([-0.7143, -1.4903, -0.9979, -0.8785, -0.1534,  1.1639, -0.7115, -0.1128,
        -0.3823, -0.3320, -0.8448, -0.4104, -0.4048, -1.3025, -0.6886, -0.7926,
        -2.1823,  0.7913, -0.9433,  0.2844, -1.0864, -0.3118, -0.3234, -0.1820,
        -0.2343,  1.8259,  1.1103, -0.2335,  0.5020,  0.3979,  1.6474, -0.1973,
        -0.5245, -0.2456, -1.2723,  1.7845,  1.2533,  0.9201, -0.1508, -0.4383,
         1.5420,  1.5182,  0.3813, -0.4135,  1.2217,  0.0029,  1.1078, -0.3327,
        -0.3839, -1.2866, -0.2851,  0.8434, -0.3501, -0.8283,  0.3126,  1.3231,
         0.2071, -0.6671, -0.1865,  0.3288, -0.0042,  0.3117, -0.0381, -0.9131,
        -0.1740, -0.0700,  0.9199,  0.8574, -0.5975, -1.5152,  0.6242,  0.5978,
         0.1579, -0.5107,  0.0757,  0.4366, -1.3448,  0.5985, -1.4366, -0.1625,
         0.3953, -1.0775, -1.1976, -1.8731,  0.2261, -0.4944, -0.7010, -0.8912,
        -0.7846,  1.6331, -1.2273, -0.1037, -0.1854, -0.9621, -0.3121, -0.1740,
         1.4625,  0.0278,  1.9579,  0.13

Matrix Multiplication

In [25]:
tensor1 = torch.tensor([[1,2],[3,4],[5,6]])
tensor2 = torch.tensor([[7,8,9],[10,11,12]])

print(f"Matrix Multiplication: \n{tensor1 @ tensor2}\n")
print(f"Matrix Multiplication: \n{torch.matmul(tensor1,tensor2)}\n")

Matrix Multiplication: 
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Matrix Multiplication: 
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

